apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "webapp-api.fullname" . }}
  labels:
    {{- include "webapp-api.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
        app: {{ include "webapp-api.fullname" . }}
    namespaceSelector:
        any: true
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 10s